### ISSUE TITLE
bugfix csrf token

### ISSUE THREAD

**Issue by laurensWe** [MinBZK/amt#146]
We notices that sometimes the csrf token is not set and therefore throws errors in AMT, right now we have a bugfix implemented in the frontend build system, but the question is, is this the right fix

**Comment by uittenbroekrobbert** [comment]
The current fix check if a csrf token is set and if not, it defaults to empty. This is ok for now.

The current CSRF implementation creates a token for each request now, which is not really needed. This is due to the 'middleware' filter chain where it is hooked, we don't know if we need a token or not. This is not really a bug, but a different way or working. I'll create a new feature for that and close this issue as the bug has been resolved.
